### ISSUE TITLE
Public repo for gregewing/apt-mirror Docker container

### ISSUE THREAD

**Issue by chjohn22** [gregewing/collectd#2]
Hi Greg
Your apt-mirror Docker container is amazing. Do you still plan to update it and implement the config files as you wrote in the container description on Docker Hub? This one does exactly do what I thought I had to invent myself. It would be wonderful if you could publish the sources here on Github or on some other git instance, which would allow us to fork it to play a bit with the config and it may possibly make the future development of this container easier.

Sorry for posting this offtopic issue in your collectd repository, I was not able to find an other way to contact you. 😃

**Comment by gregewing** [comment]
Yes I do plan to keep it up to date and publish the bandwidth management scripts. I’ve had a busy time with lockdown,  home schooling two kids at different age groups and living  in a tiny house while I build a proper one. :)

I’ll get the GitHub and the image updated this week for you.

And thanks very much for your email. It’s not often I get such glowing support :-D

Thanks and Regards
Greg Ewing
________________________________
From: chjohn22 ***@***.***>
Sent: Monday, April 19, 2021 11:10:31 PM
To: gregewing/collectd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gregewing/collectd] Public repo for gregewing/apt-mirror Docker container (#2)


Hi Greg
Your apt-mirror Docker container is amazing. Do you still plan to update it and implement the config files as you wrote in the container description on Docker Hub? This one does exactly do what I thought I had to invent myself. It would be wonderful if you could publish the sources here on Github or on some other git instance, which would allow us to fork it to play a bit with the config and it may possibly make the future development of this container easier.

Sorry for posting this offtopic issue in your collectd repository, I was not able to find an other way to contact you. 😃

**Comment by gregewing** [comment]
As requested I've described the scripts and provided them on github here :  https://github.com/gregewing/apt-mirror  

Let me know if you there's anything I should describe better.

**Comment by gregewing** [comment]
closing as separate repo published for requested image.
